## #3.1 포트폴리오의 기대수익률과 위험

Markowitz's MPT(Modern Portfolio Theory) - <*`Portfolio Selection`*>

Pareto optimal risk-return (파레토 최적 리스크-수익) 조합

### 3.1.1 두 개의 주식으로 구성된 portfolio

Consider a portfolio consisting of two stocks $A, B$ with weights $w_A, w_B$ and with individual expected returns $r_A, r_B$, respectively.

An expected return(기대 수익률) $r_p$ of the portfolio is:
$$
    r_p = w_A r_A + w_B r_B
$$

In [1]:
# initial settings
# expected returns for each stock; bull/neutral/bear market resp.
stock_a = [0.07, 0.04, 0.01]
stock_b = [0.13, 0.04, -0.05]
prob = [1/3, 1/3, 1/3]

ex_a = 0.0
ex_b = 0.0
wgt_a = 0.5
wgt_b = 0.5

In [2]:
for s, p in zip(stock_a, prob):
    ex_a += s*p

ex_a

0.04

In [3]:
# inline for loop
ex_a = sum(s*p for s, p in zip(stock_a, prob))

ex_a

0.04

In [4]:
ex_b = sum(s*p for s, p in zip(stock_b, prob))

ex_b

0.04000000000000001

In [5]:
# expected return(기대수익률) of a portfolio
ex_p = wgt_a * ex_a + wgt_b * ex_b
ex_p

0.04000000000000001

In [6]:
print('주식 A의 기대수익률은 {:.2%}'.format(ex_a))
print('주식 B의 기대수익률은 {:.2%}'.format(ex_b))
print('포트폴리오의 기대수익률은 {:.2%}'.format(ex_p))

주식 A의 기대수익률은 4.00%
주식 B의 기대수익률은 4.00%
포트폴리오의 기대수익률은 4.00%


In [7]:
import numpy as np

prob = np.matrix([1/3, 1/3, 1/3])
stock_a = np.matrix([7, 4, 1])
stock_b = np.matrix([13, 4, -5])

ex_a = prob * stock_a.T
ex_b = prob * stock_b.T

print('주식 A의 기대수익률은 %.2f%%' % ex_a)
print('주식 B의 기대수익률은 %.2f%%' % ex_b)

주식 A의 기대수익률은 4.00%
주식 B의 기대수익률은 4.00%


now (to extend this method by using `np.matrix` in the future,) we compute the expected return of the whole portfolio consitsting of stock A & B with assigned weights:

In [8]:
weight = np.matrix([0.5, 0.5])

ex_ab = np.matrix([[ex_a.item(), ex_b.item()]])

ex_p = weight * ex_ab.T

print('포트폴리오의 기대수익률은 %.2f%%' % ex_p)

포트폴리오의 기대수익률은 4.00%


In [9]:
weight = np.matrix([0.5, 0.5])

# ax_ab = np.matrix([[np.asscalar(ex_a), np.asscalar(ex_b)]])
ex_ab = np.matrix([[ex_a.item(), ex_b.item()]])

ex_p = weight * ex_ab.T

print('포트폴리오의 기대수익률은 %.2f%%' % ex_p)

포트폴리오의 기대수익률은 4.00%


### 포트폴리오의 위험 p 105
Let's compute the associated variance, covariance and correlation:

$$
    \sigma_p^2 = w_1^2 \sigma_1^2 + w_2^2 \sigma_2^2 + 2w_1w_2\sigma_{12}
$$

here, $\sigma_{12}$ is Cov(, )

$$
    \sigma_p^2 = w_1^2 \sigma_1^2 + w_2^2 \sigma_2^2 + 2w_1w_2 \sigma_1 \sigma_2 \rho_{12}
$$

where the correlation is $\rho_{12} = \frac{\sigma_{12}}{\sigma_1 \sigma_2}$.

In [19]:
import math

stock_a = [0.07, 0.04, 0.01]
stock_b = [0.13, 0.04, -0.05]
prob = [1/3, 1/3, 1/3]

ex_a = 0.0
ex_b = 0.0

# for s, p in zip(stock_a, prob):
    # ex_a += s*p
ex_a = sum(s*p for s, p in zip(stock_a, prob))
ex_b = sum(s*p for s, p in zip(stock_b, prob))
print(ex_a, ex_b)

0.04 0.04000000000000001


In [15]:
var_a, var_b = 0.0, 0.0
wgt_a, wgt_b = 0.5, 0.5

for s, p in zip(stock_a, prob):
    var_a += p*(s-ex_a)**2
print(var_a)

0.0006000000000000001


In [17]:
var_a = sum(p*(s-ex_a)**2 for s, p in zip(stock_a, prob))
var_b = sum(p*(s-ex_b)**2 for s, p in zip(stock_b, prob))

print(var_a, var_b)
print('주식 A의 분산은 {:.2%}'.format(var_a))
print('주식 B의 분산은 {:.2%}'.format(var_b))

0.0006000000000000001 0.0054
주식 A의 분산은 0.06%
주식 B의 분산은 0.54%


In [18]:
cov = sum(p*(a-ex_a)*(b-ex_b) for a, b, p in zip(stock_a, stock_b, prob))  # definition of Covariance
var_p = wgt_a**2 * var_a + wgt_b**2 * var_b + 2 * wgt_a * wgt_b * cov
std_p = math.sqrt(var_p)
print('포트폴리오의 분산은 {:.2%}'.format(var_p))
print('포트폴리오의 표준편차는 {:.2%}'.format(std_p))

포트폴리오의 분산은 0.24%
포트폴리오의 표준편차는 4.90%


In [27]:
# print('Cov(stock_a, stock_b) is {:.2%}'.format(cov))
print(f'Cov(stock_a, stock_b) is: {cov:.2%}')

Cov(stock_a, stock_b) is 0.18%
Cov(stock_a, stock_b) is: 0.18%


In [32]:
# digression - using numpy, this calculation becomes easy
import numpy as np

variance_a = np.var(stock_a)
variance_b = np.var(stock_b)
print("자산 a의 분산:", variance_a)
print("자산 b의 분산:", variance_b)

std_dev_a = np.std(stock_a)
std_dev_b = np.std(stock_b)
print("자산 a의 표준편차:", std_dev_a)
print("자산 b의 표준편차:", std_dev_b)

cov_ab = np.cov(stock_a, stock_b)
print("두 자산 a, b의 Cov", cov_ab)

자산 a의 분산: 0.0006000000000000002
자산 b의 분산: 0.005399999999999999
자산 a의 표준편차: 0.024494897427831785
자산 b의 표준편차: 0.07348469228349534
두 자산 a, b의 Cov [[0.0009 0.0027]
 [0.0027 0.0081]]


In [33]:
cov_ab

array([[0.0009, 0.0027],
       [0.0027, 0.0081]])

### 3.1.2 $n$ 개의 주식으로 만든 포트폴리오
$n$ 개의 자산으로 구성된 포트폴리오의 수익률:
$$
    r_p = w_1r_1 + w_2r_2 + \ldots + w_nr_n
$$

$n$ 개의 자산으로 구성된 포트폴리오의 기대수익률:
$$
    E(r_p) = w_1E(r_1) + w_2E(r_2) + \ldots + w_nE(r_n)
$$

In [34]:
# 포트폴리오 기대수익률 계산
import numpy as np

numStocks = 3

# 3 represents three states: bear/neutral/bull market
returns = np.random.randn(3, numStocks)
print('1. 난수로 만드는 국면별 주식의 수익률: \n', returns)

1. 난수로 만드는 국면별 주식의 수익률: 
 [[-1.05806373 -0.25223004 -0.60325559]
 [ 0.17403838 -0.82321254  0.11095813]
 [-0.70411724 -0.0776854  -0.25076092]]
